name: Playwright API and UI Testing #name of github action

#the trigger is a push on branch main
on:
  push:
    branches:
      - main

#the trigger is a schedule
#on:
  #schedule:
    #- cron: "0 0 * * *" #schedule the github action to run everyday at 0 minute 0 hour UTC

#jobs of agent
jobs:
  playwright-testing: #arbitrary name for the job
    runs-on: windows-latest #runs on latest version of windows, linux latest is missing a lot of dependencies for playwright
    steps:
      #Step 1 checkout repo, there is specific syntax for this 'uses' and 'actions/checkout@v3'
      - name: checkout repo
        uses: actions/checkout@v3

      #Step 2 set up node.js, there is specific syntax for this 'uses' and 'actions/setup-node@v3' and include a node version, "node" is used for latest
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "node"

      #Step 3 install node packages using npm install, this uses 'run' keyword for command line interactions just like running 'npm install' on terminal
      - name: install node packages
        run: npm install

      #Step 4 install playwright, the node packages do not automatically install playwright
      - name: install playwright
        run: npx playwright install

      #Step 5 run all playwright tests in directory /tests
      - name: run playwright tests
        env:
          SIGNUP_USERNAME: ${{secrets.SIGNUP_USERNAME}}
          SIGNUP_EMAIL: ${{secrets.SIGNUP_EMAIL}}
          SIGNUP_PASSWORD: ${{secrets.SIGNUP_PASSWORD}}
          EXISTING_USERNAME: ${{secrets.EXISTING_USERNAME}}
          EXISTING_EMAIL: ${{secrets.EXISTING_EMAIL}}
          EXISTING_PASSWORD: ${{secrets.EXISTING_PASSWORD}}
        run: npx playwright test tests

      #Step 6 if github actions fail then upload the report generated by playwright
      - name: upload report if failed playwright testing
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/


