name: Playwright Tests

on:
  push: # Trigger the workflow on any push event
    branches:
      - main # Specify the branch (e.g., "main"). Add more branches if needed.

jobs:
  test:
    runs-on: windows-latest # Use a Linux-based environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'node' # Specify the Node.js version required for your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Playwright
      - name: Install Playwright
        run: npx playwright install

      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Optional: Step 6: Upload Playwright test results (if enabled in your config)
      - name: Upload Playwright results
        if: failure() # Only upload results if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/